<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MpFavouriteSeller
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->
<div class="wk-mp-design">
	<fieldset class="fieldset info wk-mp-fieldset">
		<legend class="legend">
			<span><?php /* @escapeNotVerified */ echo __('My Favourite Sellers') ?></span>
		</legend>
		<div class="grid">
			<div class="hor-scroll">
				<form action="<?php /* @escapeNotVerified */ echo $block->getCurrentSiteUrl()?>" method="get" id="form-productlist-filter"  name="formFavouriteSellerFilter" data-mage-init='{"validation":{}}'>
					<table cellspacing="0" class="border wk-mp-list-table">
					    <thead>
					        <tr id="wk-mp-tr-heading">
					            <th><span><?php /* @escapeNotVerified */ echo __('Seller Name') ?></span></th>
					            <th><span>&nbsp;</span></th>
					        </tr>
					    </thead>
					    <tbody class="wk-mp-body">
					    	<tr>
					    		<td>
					    			<input type="text" class="input-text" name="s" placeholder='<?php /* @escapeNotVerified */ echo __('search by seller name') ?>' value="<?php /* @escapeNotVerified */ echo $block->getFilterParam() ?>"/>
					    		</td>
					    		<td>
					    			<button class="button" title="Save" type="submit">
										<span><span><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></span></span>
									</button>
					    		</td>
					    	</tr>
					    </tbody>
					</table>
				</form>
				<?php if ($block->getWkFavouriteSellerList() && count($block->getWkFavouriteSellerList())): ?>
					<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('mpfavouriteseller/favouriteseller/massDelete', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-favouriteseller-massdelete" name="formFavouriteSellerMassDelete" data-mage-init='{"validation":{}}'>
						<?php /* @escapeNotVerified */ echo $block->getBlockHtml('formkey')?>
						<button class="button" title="<?php echo __('Delete Sellers') ?>" type="submit" style="float: left;padding: 5px 5px 5px 0;"  id="mass-delete-butn">
							<span><span><?php /* @escapeNotVerified */ echo __('Delete Sellers') ?></span></span>
						</button>
						<table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
						    <thead>
						        <tr class="wk-content">
						        	<th class="wk-check-first-td">
						    			<span>
											<input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
										</span>
						    		</th>
						    		<th class="wk-first-td">

						    		</th>
						    		<th>
						    			<span class="label pro-status">
											<?php /* @escapeNotVerified */ echo __('Seller Name')?>
										</span>
						    		</th>
						    		<th>
						    			<span class="label pro-status">
											<?php /* @escapeNotVerified */ echo __('Seller Collection')?>
										</span>
						    		</th>
						    		<th>
						    			<span class="label">
											<?php /* @escapeNotVerified */ echo __('Action')?>
										</span>
						    		</th>			    		
						    	</tr>
						    </thead>
						    <tbody>
						    	<?php 
						    	$i = 0;
								foreach($block->getWkFavouriteSellerList() as $seller){
									$i++;
									?>
							    	<tr class="wk-row-view <?php echo $class = ($i == count($block->getWkFavouriteSellerList()))? 'wk-last_tr':''?>">
							    		<td class="wk-check-first-td">
							    			<span>
												<input type="checkbox" name="seller_mass_delete[]" class="mpcheckbox" value="<?php /* @escapeNotVerified */ echo $seller->getSellerId(); ?>"/>
											</span>
							    		</td>
							    		<td class="wk-first_td">
											<input type="hidden" class="hidden-id" value="<?php /* @escapeNotVerified */ echo $seller->getSellerId(); ?>" />
											<div class="label name">
												<div class="wk-pro-divide1">
													<a href="<?php /* @escapeNotVerified */ echo $block->getSellerProfileUrl($seller->getShopUrl()) ?>" title="<?php /* @escapeNotVerified */ echo $seller->getShopUrl() ?>">
														<img class="image" src="<?php /* @escapeNotVerified */ echo $block->getSellerLogo($seller->getLogoPic()) ?>" alt="no-image">
													</a>
												</div>
											</div>
							    		</td>
							    		<td>		
											<span class="label pro-status">
												<?php /* @escapeNotVerified */ echo $block->getCustomerName($seller->getSellerId())?>
											</span>
										</td>
										<td>		
											<a href="<?php /* @escapeNotVerified */ echo $block->getSellerCollectionUrl($seller->getShopUrl())?>"><?php echo __('Collection');?>
											</a>
										</td>
							    		<td>
							    			<span class="label wk-action">
												<img src="<?php /* @escapeNotVerified */ echo $this->getViewFileUrl('Webkul_Marketplace::images/icon-trash.png'); ?>" alt="<?php /* @escapeNotVerified */ echo __('Delete')?>" title="<?php /* @escapeNotVerified */ echo __('Delete')?>" class="mp-delete" data-url="<?php /* @escapeNotVerified */ echo $block->getUrl('mpfavouriteseller/favouriteseller/delete/', ['id'=>$seller->getSellerId(), '_secure' => $this->getRequest()->isSecure()]) ?>"/>
											</span>	
							    		</td>			    		
							    	</tr>
							    	<?php
							    }?>
						    </tbody>
						</table>
					</form>						
				<?php else: ?>
					<div class="wk-emptymsg">
						<?php /* @escapeNotVerified */ echo __('No Favourite Seller Available') ?>
					</div>
				<?php endif ?>					
			</div>
		</div>
		<?php if ($block->getPagerHtml()): ?>
	        <div class="order-products-toolbar toolbar bottom"><?php /* @escapeNotVerified */ echo $block->getPagerHtml(); ?></div>
	    <?php endif ?>	
	</fieldset>	
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "favouriteSellerList": {}
        }
    }
</script>