<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MarketplacePreorder
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk-loading-mask wk-display-none">
    <div class="wk-loader"></div>
</div>
<?php
    $helper = $this->helper('Webkul\MarketplacePreorder\Helper\Data');
    $configHelper = $this->helper('Webkul\MarketplacePreorder\Helper\Config');
    $productId = $this->getProduct()->getId();
    $flag = 0;
    $configFlag = 0;
    if($helper->isPreorder($productId)) {
        $flag = 1;
    }
    $html = '';
    if($helper->isConfigPreorder($productId)) {
        $configFlag = 1;
        $configMsg = __('Product has preorder option(s)');
        $html = "<div class='wk-config-msg-box wk-info'>";
        $html .= $configMsg;
        $html .= '</div>';
    }
    $payHtml = $helper->getPayPreOrderHtml($productId);
    $msg = $helper->getPreOrderInfoBlock($productId);
    $configMsg = $html;
    $url = $helper->getCheckConfigUrl();
    $data = json_encode(["payHtml" => $payHtml, "msg" => $msg, 'configmsg' => $configMsg, "flag" => $flag, 'config' => $configFlag, "url" => $url]);
?>
<script>
    window.preorderData = <?php echo \Zend_Json::encode($configHelper->getPreorderConfigData($productId)); ?>
</script>
<script type="text/x-magento-init">
    {
        "body": {
            "Webkul_MarketplacePreorder/js/pageview": <?php echo $data ?>
        }
    }
</script>