<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpFavouriteSeller
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$allow_pro_type=$_helper->getAllowedProductType();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();

?>
<style type="text/css">
    @media only screen and (max-width: 767px){

        .block-collapsible-nav.wk-mp-main{
            top: 20px;
        }
    }
</style>

<nav class="account-nav">
    <ul class="nav items">
        <?php 
        if($isPartner){ ?>
            <?php if(($isSellerGroup && $_helper->isAllowedAction('mpfavouriteseller/shopfollower/index')) || !$isSellerGroup) { ?>
            <li class="nav item <?php echo strpos($magentoCurrentUrl,'mpfavouriteseller/shopfollower/index')? "current":"";?>">      
                    <a href="<?php echo $block->getUrl('mpfavouriteseller/shopfollower/index', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                        <?php /* @escapeNotVerified */ echo __('Shop Followers') ?>
                    </a>                                     
            </li>
            <?php } ?>
        <?php } ?>
    </ul>
</nav>


