<?php
    /**
    * Webkul Software.
    *
    * @category  Webkul
    * @package   Webkul_Marketplace
    * @author    Webkul
    * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
    * @license   https://store.webkul.com/license.html
    */

    // @codingStandardsIgnoreFile
    $categories = $block->getCategoryIds();
    $formData = [
        "categories"		  => implode(",", $categories),
        "categoryTreeAjaxUrl" => $block->getUrl("mobikul/featuredcategories/categorytree/", ["_secure"=>$this->getRequest()->isSecure()])
    ];
    $serializedFormData = $this->helper("Magento\Framework\Json\Helper\Data")->jsonEncode($formData);               ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "featuredCategories": <?php /* @noEscape */ echo $serializedFormData; ?>
            }
        }
    </script>