<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Mpfreeshipping
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php if($block->getConfigData('active') && $block->getConfigData('allow_seller')): ?>
    <form class="form-shipping" action="<?php /* @escapeNotVerified */ echo $block->getUrl('freeshipping/shipping', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    	<fieldset class="fieldset info">
			<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Manage Free Shipping') ?></span>
	        	<button type="submit" class="button wk-mp-btn action save primary">
					<span><span><?php echo __('Save') ?></span></span>
				</button>
	        </legend><br>
			<?php echo $block->getBlockHtml('formkey')?>
			<div class="field required">
            	<label for="mp_freeshipping_amount" class="label"><span><?php echo __("Minimum Order Amount"); ?>:</span></label>
                <div class="control">
                    <input id="mp_freeshipping_amount" class="required-entry validate-number validate-zero-or-greater input-text" type="text" name="mp_freeshipping_amount" data-validate="{required:true, 'validate-number':true}" value="<?php echo $block->_getCustomerData()->getMpFreeshippingAmount(); ?>" />
                </div>
            </div>
		</fieldset>
	</form>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        }
    }
</script>