<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_Mpcashondelivery
 * @author Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
$_item = $block->getItem();
$product = $_item->getProduct();
$helper = $block->getMpHelper();
$codHelper = $block->getMpCodHelper();
$productId = $product['entity_id'];
$sellerId = 0;
$getPaymentEnable = $codHelper->getCodEnable();
if ($getPaymentEnable && $product['type_id'] != 'virtual') {
    $marketplaceProduct = $helper->getSellerProductDataByProductId($product['entity_id']);
    foreach ($marketplaceProduct as $value) {
        $sellerId = $value['seller_id'];
    }
    $prodCodAvailable = $codHelper->getCodAvailablility($_item->getQty()*$_item->getWeight(),$sellerId);
    $productCodAvailable = $codHelper->getProductCodAvailable($productId);
    if($productCodAvailable && $prodCodAvailable){ ?>
            <div class="wk-seller-block wk-block" id="mp-wk-block">
                <div>
                    <?php /* @escapeNotVerified */echo __('CASH ON DELIVERY'); ?>
                    <img src="<?php /* @escapeNotVerified */echo $block->getViewFileUrl('Webkul_Marketplace::images/quest.png');?>" class='questimg' title="<?php /* @escapeNotVerified */echo $codHelper->getCodDescription() ?>"/>
                </div>
            </div>
            <?php
    }else{ ?>
            <div style="width:100%;color:red;">
                <?php /* @escapeNotVerified */echo __('CASH ON DELIVERY NOT AVAILABLE'); ?>
            </div>
            <?php
    }
}