<?php 
echo $block->getChildHtml();
$storeId = $this->getRequest()->getParam('store');
if (!$storeId) {
    $storeId = 0;
}
$sellerId = $this->getRequest()->getParam('id');
$helper = $this->helper('Webkul\SellerSubDomain\Helper\Data');
$currentDomain = $helper->getCurrentDomainUrl($this->getRequest()->getParam('store'), $sellerId);

?>
<div class="admin__fieldset-wrapper opened">
	<div class="admin__fieldset-wrapper-content">
        <fieldset class="admin__fieldset">
            <div class="admin__field">
                <label class="admin__field-label"><?php echo __('Vendor Domain') ?>:</label>
                <div class="admin__field-control">
                    <input data-form-part="customer_form" class="admin__control-text validate-url wk-elements" type="text" name="vendor_domain" value='<?php echo $currentDomain; ?>' />
                </div>
            </div>   
        </fieldset>
    </div>
<div>