<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_Mpcashondelivery
 * @author Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */

$_helper = $block->getMpHelper();
$orderHelper = $block->getMpCodOrderHelper();
$codHelper = $block->getMpCodHelper();
$isPartner= $_helper->isSeller();
$getPaymentEnable = $codHelper->getCodEnable();
?>
<?php if($isPartner==1){ 
	$filter_orderid = '';
    $filter_orderstatus = '';
    $filter_data_to = '';
    $filter_data_frm = '';
    $paramData = $this->getRequest()->getParams();
    if(isset($paramData['s'])){
        $filter_orderid = $paramData['s'] != ""?$paramData['s']:"";
    }
    if(isset($paramData['orderstatus'])){
        $filter_orderstatus = $paramData['orderstatus'] != ""?$paramData['orderstatus']:"";
    }
    if(isset($paramData['from_date'])){
        $filter_data_frm = $paramData['from_date'] != ""?$paramData['from_date']:"";
    }
    if(isset($paramData['to_date'])){
        $filter_data_to = $paramData['to_date'] != ""?$paramData['to_date']:"";
    }
		if($getPaymentEnable){?>
			<div class="wk-mp-design">
				<div class="block block-account">	
					<div class="block-title">	
						<strong><span><h4><?php /* @escapeNotVerified */echo __('Order History') ?></h4></span></strong>
					</div>
				</div>
				<fieldset class="fieldset wk-mp-fieldset">
					<div class="grid">
						<div class="hor-scroll">
							<form action="<?php /* @escapeNotVerified */echo $block->getCurrentUrl();?>" method="get">
								<table cellspacing="0" class="border wk-mp-list-table">
								    <thead>
								        <tr id="wk-mp-tr-heading">
								            <th><span><?php /* @escapeNotVerified */echo __('Order Id') ?></span></th>
								            <th><span><?php /* @escapeNotVerified */echo __('Date') ?></span></th>
								            <th><span><?php /* @escapeNotVerified */echo __('Order Status') ?></span></th>
								            <th><span>&nbsp;</span></th>
								        </tr>
								    </thead>
								    <tbody class="wk-mp-body">
								    	<tr>
								    		<td>
								    			<input type="text" class="input-text" name="s" placeholder='<?php /* @escapeNotVerified */echo __('Search by Order Id') ?>' value="<?php /* @escapeNotVerified */echo $filter_orderid?>" style="width:99%;"/>
								    		</td>
								    		<td>
								    			<span class="wk-mp-td-span">
								    				<input name="from_date" id="special-from-date" class="input-text" value="<?php /* @escapeNotVerified */echo $filter_data_frm?>" type="text" placeholder='<?php /* @escapeNotVerified */echo __('Date From') ?>' />
								    			</span>
								    			<span class="wk-mp-td-span">
								    				<input name="to_date" id="special-to-date" class="input-text" value="<?php /* @escapeNotVerified */echo $filter_data_to?>" type="text" placeholder='<?php /* @escapeNotVerified */echo __('Date To') ?>' />
								    			</span>
								    		</td>
								    		<td>
							    				<select name="orderstatus" class="input-text">
							    					<option value=""><?php /* @escapeNotVerified */echo __('All') ?></option>
							    					<?php 
							    					$orderstatus_coll = $block->getOrderStatusData();
							    					foreach ($orderstatus_coll as $orderstatus) {
							    						?>
							    						<option value="<?php /* @escapeNotVerified */echo $orderstatus['status']?>" <?php if($filter_orderstatus == $orderstatus['status']) /* @escapeNotVerified */echo 'selected="selected"'?>>
									    					<?php /* @escapeNotVerified */echo $orderstatus['label'] ?>
									    				</option>
							    						<?php
							    					}
							    					?>
								    			</select>
								    		</td>
								    		<td>
								    			<button class="button" title="Save" id="save_butn" type="submit">
													<span><span><span><?php /* @escapeNotVerified */echo __('Submit') ?></span></span></span>
												</button>
								    		</td>
								    	</tr>
								    </tbody>
								</table>
							</form>
							<?php 
							if(count($block->getCodOrderCollection())==0){ ?>		
								<div class="fieldset wk-mp-fieldset">
									<div class="wk_emptymsg">
										<?php /* @escapeNotVerified */echo __('No Order Available') ?>
									</div>
								</div>
								<?php 
							} else{ ?>
								<div class="table-wrapper">
									<table class="data table orders wk-mp-list-table" id="my-orders-table-cod">
										<thead>
											<tr>
												<th><?php /* @escapeNotVerified */echo __('Order #') ?></th>
												<th><?php /* @escapeNotVerified */echo __('Date') ?></th>
												<th><?php /* @escapeNotVerified */echo __('Ship To') ?></th>
												<th><span class="nobr"><?php /* @escapeNotVerified */echo __('Order Total') ?></span></th>
												<th><span class="nobr"><?php /* @escapeNotVerified */echo __('Order Status') ?></span></th>
												<th><span class="nobr"><?php /* @escapeNotVerified */echo __('Collected COD') ?></span></th>
												<th><span class="nobr"><?php /* @escapeNotVerified */echo __('Commission Paid To Admin') ?></span></th>
												<th>&nbsp;</th>
											</tr>
										</thead>
										<tbody>
											<?php $_odd = ''; ?>
											<?php $i=0;
											foreach($block->getCodOrderCollection() as $res){
												$_order = $block->getOrder($res['order_id']);
												$status=$_order->getStatus();
												$name=$_order->getCustomerName();
												if($res['order_id']>0){
													$i++;?>
													<tr>
														<td data-th="<?php echo __('Order #') ?>" scope="col" class="col"><?php /* @escapeNotVerified */echo $_order->getRealOrderId() ?></td>
														<td data-th="<?php echo __('Date') ?>" scope="col" class="col"><span class="nobr"><?php /* @escapeNotVerified */echo $block->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
														<td data-th="<?php echo __('Ship To') ?>" scope="col" class="col"><?php /* @escapeNotVerified */echo $_order->getShippingAddress() ? $_order->getShippingAddress()->getName() : '&nbsp;' ?></td>
														<td data-th="<?php echo __('Order Total') ?>" scope="col" class="col"><?php /* @escapeNotVerified */echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
														<td data-th="<?php echo __('Order Status') ?>" scope="col" class="col"><em><?php /* @escapeNotVerified */echo $_order->getStatusLabel() ?></em></td>
														<td data-th="<?php echo __('Collected COD') ?>" scope="col" class="col">
															<em>
																<?php
																if($res['collect_cod_status']==1){
																	/* @escapeNotVerified */echo __('Collected');
																}else if($res['collect_cod_status']==2){
																	/* @escapeNotVerified */echo __('Canceled');
																}else if($res['collect_cod_status']==3){
																	/* @escapeNotVerified */echo __('Refunded');
																}else{
																	/* @escapeNotVerified */echo __('Pending');
																}?>
															</em>
														</td>
														<td data-th="<?php echo __('Commission Paid To Admin') ?>" scope="col" class="col">
															<em>
																<?php 
																if($res['admin_pay_status'] == 1){
																	/* @escapeNotVerified */echo __('Paid');
																}else if($res['admin_pay_status']==2){
																	/* @escapeNotVerified */echo __('Canceled');
																}else{
																	/* @escapeNotVerified */echo __('Pending');
																}?>
															</em>
														</td>
														<td data-th="<?php echo __('Action') ?>" scope="col" class="col" class="a-center">
															<span class="nobr">
																<a href="<?php /* @escapeNotVerified */echo $block->getUrl('marketplace/order/view',['id'=>$res['order_id']])?>" title="<?php /* @escapeNotVerified */echo __('View Order') ?>">
																	<?php /* @escapeNotVerified */echo __('View Order') ?>
																</a>
															</span>
														</td>
													</tr>
												<?php 
												}
											} ?>
										</tbody>
									</table>
								<?php
							}?>
						</div>
					</div>
					<div class="order-products-toolbar toolbar bottom">
					<?php /* @escapeNotVerified */echo $block->getPagerHtml(); ?>
					</div>
				</fieldset>	
				<div class="buttons-set">
					<p class="back-link">
						<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php /* @escapeNotVerified */echo __('Back') ?></a>
					</p>
				</div>
			</div>
		<?php }else{
			/* @escapeNotVerified */echo "<h2 class='wk_new_msg'>".__("Payment method is currently disabled.")."</h2>";
		}
}else{
	/* @escapeNotVerified */echo "<h2 class='wk_new_msg'>".__("To BECOME SELLER PLEASE CONTACT TO ADMIN.")."</h2>";
}?>
<script>
	    require([
	        "jquery",
	        "mage/mage",
        	'mage/calendar'
	    ], function($){
	    	$("#special-from-date").calendar({'dateFormat':'mm/dd/yy'});
			$("#special-to-date" ).calendar({'dateFormat':'mm/dd/yy'});
			$(document).ready(function(){
				$('#save_butn').click(function () {
					var startDate = $("#special-from-date").val();
					var endDate = $('#special-to-date').val();
					if (new Date(startDate) > new Date(endDate)) {
						alert('From Date must be prior than To Date.');
						return false;
					}
				})
			})
});    
</script>