<?php 
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_Mpcashondelivery
 * @author Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */

$_helper = $block->getMpHelper();
$codHelper = $block->getMpCodHelper();
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$getPaymentEnable = $codHelper->getCodEnable();
?>
<?php 
    if($getPaymentEnable && $isPartner){ ?>
    <li class="mpcodnav nav item <?php /* @escapeNotVerified */echo strpos($magentoCurrentUrl,'mpcashondelivery') !== false ? "current":"";?>">
        <?php if(strpos($magentoCurrentUrl,'mpcashondelivery') !== false){ ?>   
            <strong><?php /* @escapeNotVerified */ echo __('Marketplace Cash On Delivery') ?></strong>        
        <?php 
        } else { ?>    
            <a href="#"><?php /* @escapeNotVerified */ echo __('Marketplace Cash On Delivery') ?></a>   
        <?php } ?>
        <ul class="nav items">
            <li class="nav item <?php /* @escapeNotVerified */echo strpos($magentoCurrentUrl,'mpcashondelivery/pricerules/index') !== false ? "current":"";?>">
           <?php 
            if(strpos($magentoCurrentUrl,'mpcashondelivery/pricerules/index') !== false){ ?>
                <strong><?php /* @escapeNotVerified */echo __('Manage Cash On Delivery Rates') ?></strong>
                <?php
            } else{ ?>
                <a href="<?php /* @escapeNotVerified */echo $block->getUrl('mpcashondelivery/pricerules/index'); ?>">
                    <?php /* @escapeNotVerified */echo __('Manage Cash On Delivery Rates') ?>
                </a>
            <?php 
                } ?>
            </li>
            <li class="nav item <?php /* @escapeNotVerified */echo strpos($magentoCurrentUrl,'mpcashondelivery/order/index') !== false ? "current":"";?>">
           <?php 
            if(strpos($magentoCurrentUrl,'mpcashondelivery/order/index') !== false){ ?>
                <strong><?php /* @escapeNotVerified */echo __('Manage Cash On Delivery Orders') ?></strong>
                <?php
            } else{ ?>
                <a href="<?php /* @escapeNotVerified */echo $block->getUrl('mpcashondelivery/order/index'); ?>">
                    <?php /* @escapeNotVerified */echo __('Manage Cash On Delivery Orders') ?>
                </a>
            <?php 
                } ?>
            </li>
            <li class="nav item <?php /* @escapeNotVerified */echo strpos($magentoCurrentUrl,'mpcashondelivery/products/index') !== false? "current":"";?>">
            <?php 
            if(strpos($magentoCurrentUrl,'mpcashondelivery/products/index') !== false){ ?>
                <strong><?php /* @escapeNotVerified */echo __('Manage Cash On Delivery Products') ?></strong>
                <?php
            } else{ ?>
                <a href="<?php /* @escapeNotVerified */echo $block->getUrl('mpcashondelivery/products/index'); ?>">
                    <?php /* @escapeNotVerified */echo __('Manage Cash On Delivery Products') ?>
                </a>
            <?php 
                } ?>
            </li>
        </ul>

<?php }?>